theme: jekyll-theme-minimal
title: usocial
logo: /assets/img/logo.svg
description: "Read. Listen. Pay back."
baseurl: ""
github:
  repository_url: https://github.com/ibz/usocial
  repository_nwo: ibz/usocial
