theme: jekyll-theme-minimal
title: usocial
logo: /assets/img/logo.png
description: "The minimalist feed reader, feed aggregator and podcast client"
baseurl: ""
github:
  repository_url: https://github.com/ibz/usocial
  repository_nwo: ibz/usocial
