theme: jekyll-theme-minimal
title: muSocial
logo: /assets/img/logo.png
baseurl: ""
github:
  repository_url: https://github.com/1984solutions/musocial
  site.github.repository_nwo: 1984solutions/musocial
