theme: jekyll-theme-minimal
title: usocial
logo: /assets/img/logo.svg
description: "Read. Listen. Pay back. The minimalist self-hosted feed reader and podcast client for your personal server. With Lightning Network support."
baseurl: ""
github:
  repository_url: https://github.com/ibz/usocial
  repository_nwo: ibz/usocial
