theme: jekyll-theme-minimal
title: musocial
logo: /assets/img/logo.png
description: "The minimalist feed reader / aggregator"
baseurl: ""
github:
  repository_url: https://github.com/ibz/musocial
  repository_nwo: ibz/musocial
